prepare_spectrum:
  enabled: true
  input_filename: "AuAgCu_15-15-70_2eV_1E19_10000res.txt"
  output_filename: "AuAgCu_15-15-70_2eV_1E19_10000res_integrals.txt"
  baseline_correction:
    ratio: 1E-5
    lam: 1000
    niter: 10
  peak_finder:
    height: 100
    wlen: 40
  plot_options:
    wl_start: 509
    wl_end: 523

gather_data:
  enabled: true
  input_filename: "AuAgCu_15-15-70_2eV_1E19_10000res_integrals.txt"
  output_filename: "AuAgCu_15-15-70_2eV_1E19_10000res_integrals_with_constants.txt"
  species: "Au;Ag;Cu"
  lower_wavelength: 300
  upper_wavelength: 900

plasma_temperature:
  enabled: true
  species_name: "Cu"
  input_filename: "AuAgCu_15-15-70_2eV_1E19_10000res_integrals_with_constants.txt"
  output_filename: "result.txt"
  ionization_energy: "Cu I"
  target_lines:
    CuI: 
      - 465.11 
      - 510.55
      - 515.32
      - 521.82
    CuII: 
      - 495.36
      - 512.18
      - 518.34
