class SpectrumLineAdapterConfig:
    url = "https://physics.nist.gov/cgi-bin/ASD/lines1.pl"
    measure_type = 0
    wavelength_units = 1
    de = 0
    output_format = 3
    remove_javascript = "on"
    energy_level_units = 0
    display_output = 0
    page_size = 15
    output_ordering = 0
    line_type_criteria = 1
    show_observed_wavelength_data = 1
    wavelength_medium = 2
    transition_strength = 0
    transition_type_allowed = 1
    level_information_energies = "on"
    submit = "Retrieve Data"
    level_information_g = "on"