name: Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Build image
        run: make build

      - name: Run Tests
        run: make test