name: Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build image
        run: make build-test

      - name: Run Tests
        run: make test-ci

      - name: Run Linting
        run: make lint